// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCc_-TolWbtz4-_Yhge867WcrJgPZhlf48',
    appId: '1:767044015900:web:8671d7fe4f677b17734cd9',
    messagingSenderId: '767044015900',
    projectId: 'amuse-app-template',
    authDomain: 'amuse-app-template.firebaseapp.com',
    storageBucket: 'amuse-app-template.firebasestorage.app',
    measurementId: 'G-KF0HJV26BH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4uReYiG_fVVDkwOmkPteF3roa_sGMHDQ',
    appId: '1:767044015900:android:cbb7e86c88e787b9734cd9',
    messagingSenderId: '767044015900',
    projectId: 'amuse-app-template',
    storageBucket: 'amuse-app-template.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbjyYZKRRjWWcBB7HhF-EEpLHl4STcMX0',
    appId: '1:767044015900:ios:a15487bd887970d6734cd9',
    messagingSenderId: '767044015900',
    projectId: 'amuse-app-template',
    storageBucket: 'amuse-app-template.firebasestorage.app',
    iosBundleId: 'com.example.amuseAppTemplate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbjyYZKRRjWWcBB7HhF-EEpLHl4STcMX0',
    appId: '1:767044015900:ios:a15487bd887970d6734cd9',
    messagingSenderId: '767044015900',
    projectId: 'amuse-app-template',
    storageBucket: 'amuse-app-template.firebasestorage.app',
    iosBundleId: 'com.example.amuseAppTemplate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCc_-TolWbtz4-_Yhge867WcrJgPZhlf48',
    appId: '1:767044015900:web:f0daef9e8ed7d2fa734cd9',
    messagingSenderId: '767044015900',
    projectId: 'amuse-app-template',
    authDomain: 'amuse-app-template.firebaseapp.com',
    storageBucket: 'amuse-app-template.firebasestorage.app',
    measurementId: 'G-Q9CETZEEBW',
  );
}
